version: '2'
services:
    mylastporn-app:
        image: mylastporn
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mylastporn-mysql:3306/mylastporn?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=mylastporn-elasticsearch:9300
        ports:
            - 8080:8080
    mylastporn-mysql:
        extends:
            file: mysql.yml
            service: mylastporn-mysql
    mylastporn-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mylastporn-elasticsearch
